name: 'PHP Insights App Internal'
description: '(internal) PHP Insights App integration with GitHub actions'
branding:
  icon: 'check-square'
  color: 'green'
runs:
  using: 'docker'
  image: 'docker://docker.pkg.github.com/worksome/phpinsights-app/phpinsights-app-action:latest'