name: Deploy Badge CloudFlare Worker

on:
  push:
    branches:
      - master
    paths:
      - 'badge/**'

jobs:
  deploy_to_cloudflare:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@master
      - name: Publish
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
          workingDirectory: 'badge'