on:
  pull_request:
  push:
    branches:
      - master

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    name: Static analysis
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: PHP Insights App
        uses: ./.github/actions/ # Uses an action in the root directory
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          workingDir: 'action'